# config/config.yaml

# Assistant Personality
assistant:
  character: "ernest"

# Keyword recognition
picovoice:
  keyword_path: "models/keyowrd.ppn"

# Webhook URLs for smart home control
webhooks:
  lights_on: "http://your-smart-home-url/api/lights/on"
  lights_off: "http://your-smart-home-url/api/lights/off"

# Elevenlabs config

elevenlabs:
  voice_id: "HKAraoM4XkoVRdCc6Iq9"
  # Ernest's voice id HKAraoM4XkoVRdCc6Iq9
  # Adam's voice id 6zicmgdIz4R8KLcDyKh5
  stability: "0.75"
  similarity_boost: "1.0"
  style: "0.40"

# Paths for static assets
static:
  listening_tone_path: "static/sounds/"
  voices: "static/voices/"

# Logging settings
logging:
  level: "INFO"
  file: "logs/assistant.log"