# config/config.yaml

# Keyword recognition
picovoice:
  keyword_path: "models/keyowrd.ppn"

# Webhook URLs for smart home control
webhooks:
  lights_on: "http://your-smart-home-url/api/lights/on"
  lights_off: "http://your-smart-home-url/api/lights/off"

# Paths for static assets
static:
  listening_tone: "static/sounds/coee.wav"
  voices: "static/voices/"

# Logging settings
logging:
  level: "INFO"
  file: "logs/assistant.log"